version: '3.7'

networks:
  net:
    driver: bridge

services:
  api:
    container_name: avito_api
    build:
      context: ./api
    environment:
      DATABASE_URL: "pgsql://test:test@postgres:5432/avito"
      REDIS_PASS: redis
      REDIS_PORT: 6379
    volumes:
      - "./api:/api"
    depends_on:
      - postgres
      - redis
    networks:
      - net

  nginx:
    container_name: avito_nginx
    build:
      context: ./api/nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - "./api:/api"
    depends_on:
      - api
    networks:
      - net
  
  postgres:
    container_name: avito_pg
    image: "postgres:13-alpine"
    volumes:
      - "pg-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=avito
    networks:
      - net

  redis:
    container_name: avito_redis
    image: redis
    restart: unless-stopped
    command:
      - "redis-server"
      - "--requirepass"
      - "redis"
      - "--maxmemory"
      - "256M"
      - "--maxmemory-policy"
      - "volatile-lfu"
    networks:
      - net
    volumes:
      - redis-data:/data

volumes:
  pg-data:
  redis-data: